# -*- coding: utf-8 -*-
"""Exercicio2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l58NftleEqfJ-1VsUG9HURudt5l9oJV8
"""

import numpy as np

anos = np.genfromtxt("anos.txt")
print(anos)

alturas = np.genfromtxt("altura.txt")
print(alturas)

idx = np.where((anos >= 1998) & (anos <= 2005))
arrayAnos = np.array(idx, dtype=int)
tamanho = arrayAnos.size
print(tamanho)
print(arrayAnos)

somaAlturas = alturas[arrayAnos].sum()
result = somaAlturas / tamanho
print(round(result, 4))