# -*- coding: utf-8 -*-
"""EX3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFKciH-_YPKuAQRuGtZRE9xdzbJKuI8W
"""

import matplotlib.pyplot as plt
import numpy as np

mes = np.arange(12) + 1 # meses de 1 a 12
creme_facial = np.array([ 2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900 ]) 
limpeza_facial = np.array([ 1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760 ]) 
pasta_dentaria = np.array([ 5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400 ])
sabonete = np.array([ 9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400 ])
shampoo = np.array([ 1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800 ])
hidratante = np.array([ 1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760 ])

cremeFacialSoma = creme_facial.sum() 
limpezaFacialSoma = limpeza_facial.sum() 
pastaDentariaSoma = pasta_dentaria.sum()
saboneteSoma = sabonete.sum()
shampooSoma = shampoo.sum()
hidratanteSoma = hidratante.sum()

# Gráfico 1 - Total de produtos Vendidos por mês - Linha
somaProdutos = creme_facial + limpeza_facial + pasta_dentaria + sabonete + shampoo + hidratante

x = mes
y = somaProdutos

fig, ax = plt.subplots()
ax.plot(x, somaProdutos, color="deeppink")
fig.set_size_inches(10, 5)
ax.set_xlabel('Meses')
ax.set_ylabel('Quantidades')
ax.set_title("Total de produtos Vendidos por mês")
ax.legend()

# Gráfico 2 - Gráfico com todos os produtos vendidos por mês - Linha
fig, ax = plt.subplots()
ax.plot(mes, creme_facial, label="Creme facial")
ax.plot(mes, limpeza_facial, label="Limpeza facial")
ax.plot(mes, pasta_dentaria, label="Pasta dentária")
ax.plot(mes, sabonete, label="Sabonete")
ax.plot(mes, shampoo, label="Shampoo")
ax.plot(mes, hidratante, label="Hdratante")

fig.set_size_inches(10, 5)
ax.set_xlabel('Meses')
ax.set_ylabel('Quantidades')
ax.set_title("Todos os produtos vendidos por mês")
ax.legend()

# Gráfico 3 - Comparativo de Creme Facial com Limpeza Facial por mês - Barras
fig, ax = plt.subplots()
largura_barra = 0.30
ax.bar(x - largura_barra/2, creme_facial, largura_barra, label="Creme Facial", color="hotpink")
ax.bar(x + largura_barra/2, limpeza_facial, largura_barra, label="Limpeza Facial", color="paleturquoise")

fig.set_size_inches(10, 5)
ax.set_xlabel('Meses')
ax.set_ylabel('Quantidades')
ax.set_title("Comparativo de Creme Facial com Limpeza Facial por mês")
ax.legend()

# Gráfico 4 - Histograma de quantidade de meses (y) e faixas de quantidades de produtos vendidos (1000-1999, 2000-2999, ...)
produtos = [creme_facial, limpeza_facial, pasta_dentaria, sabonete, shampoo, hidratante]
fig, ax = plt.subplots()
ax.hist(produtos, edgecolor="white")
fig.set_size_inches(10, 5)
ax.set_xlabel('Quantidades')
ax.set_ylabel('Meses')
ax.set_title("Quantidade de meses e faixas de quantidades de produtos vendidos")
ax.legend()

# Gráfico 5 - Pizza. % da quantidade produtos vendidos no ano em cada produto
arrayTodos = np.array([cremeFacialSoma, limpezaFacialSoma, pastaDentariaSoma, saboneteSoma, shampooSoma, hidratanteSoma])

textos = ["Creme Facial", "Limpeza Facial", "Pasta Dentária", "Sabonete", "Shampoo", "Hidratante"]
explodir = [0, 0, 0, 0.15, 0, 0 ]

fig, ax = plt.subplots()

ax.pie(arrayTodos, labels = textos, explode=explodir, shadow=True, autopct="%1.1f%%")

fig.show()