# -*- coding: utf-8 -*-
"""ex5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE2tCa7YZXXrqdyUVpv6A-2XTiZiaVYG
"""

import pandas as pd
import numpy as np

# 1. importar os dados de CSV do dataset de seeds:
seeds = pd.read_csv('https://raw.githubusercontent.com/celsocrivelaro/simple-datasets/main/seeds.csv',index_col=None ,header=None)

# 2. colocar as linhas de cabeçalho: 
  # 1. Área A,
  # 2. Perímetro P,
  # 3. Extensão do núcleo,
  # 4. Largura,
  # 5. Coeficiente de Assimetria
  # 6. Extensão do sulgo do núcleo.
seeds.columns = ['Área A',
                 'Perímetro P',
                 'Extensão do núcleo',
                 'Largura',
                 'Coeficiente de Assimetria',
                 'Extensão do sulgo do núcleo',
                 '1',
                 '2',
                 '3']

# 3. remover colunas extras no final
seeds = seeds.drop('1',axis=1)
seeds = seeds.drop('2',axis=1)
seeds = seeds.drop('3',axis=1)

# 4. remover as linhas com valores nulos
seeds.dropna(inplace=True)

# 5. Adicionar um campo Compactação cujo o cálculo é C = 4*pi*A/P^2
seeds["Campo Compactação"] = 4 * np.pi * seeds["Área A"]/seeds["Perímetro P"]**2

# 6. Exportar para CSV o valor final
seeds.to_csv('D:\seedsCSV\seeds.csv')

print(seeds)